# Generated by Django 4.2.5 on 2023-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Winery', models.CharField(max_length=500)),
                ('Variety', models.CharField(max_length=500)),
                ('Image', models.CharField(max_length=500)),
                ('Region', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
                ('Year', models.IntegerField(default=2023)),
                ('Totalqualifications', models.IntegerField(default=0)),
                ('Avgqualifications', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
    ]
