# Generated by Django 4.2.5 on 2023-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='Score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
